pipelines:
  default:
    - step:
        name: Build documentation
        image: julia:latest
        caches:
          - julia-home
        script:
          - apt-get update
          - apt-get install -y git
          - julia --project -e "import Pkg; Pkg.instantiate()"
          - julia --project -e "using Documenter; document = Documenter.Documents.Document(); @show document.user.root"
          - julia --project "docs/make.jl"
          - chmod +x ./publish_styleguide.sh
          - ./publish_styleguide.sh
definitions:
  caches:
    julia-home: ~/.julia
